name: llscheck

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
    - main
  push:
    branches:
      - main

jobs:
  llscheck:
    runs-on: ubuntu-latest
    name: llscheck

    steps:
    - uses: actions/checkout@master
      with:
        submodules: true  # Ensure submodules are checked out

    - name: Update Submodules
      run: git submodule update --init --recursive

    - uses: leafo/gh-actions-lua@v10
      with:
        luaVersion: "luajit-openresty"

    - name: Install lua-language-server
      uses: jdx/mise-action@v2
      with:
        tool_versions: |
          lua-language-server latest

    - uses: leafo/gh-actions-luarocks@v4
    - name: Install llscheck
      run: |
        luarocks install llscheck

    - name: test
      run: |
        llscheck --configpath .luarc.json .
